name: loader
description: Run asynchronous code before building your widget. Loader will rebuild your widget after the loading is complete.
version: 0.3.4+1
author: Ali Ghanabri <ali.gh2236@gmail.com>
homepage: https://github.com/ali2236/loader

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter