name: loader
description: Run asynchronous code before building your widget. Loader will rebuild your widget after the loading is complete.
version: 0.1.0+1
author: Ali Ghanabri <ali.gh2236@gmail.com>
homepage: https://aligator.ir

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
